AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  kioskng-api
  Sample SAM Template for kioskng-api
  
Globals:
  Function:
    Timeout: 3

Resources:
  ProductDynamoDBAccess:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: ProductDynamoDBAccess
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: ReadWriteTable
            Effect: Allow
            Action:
              - dynamodb:BatchGetItem
              - dynamodb:GetItem
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:BatchWriteItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
            Resource: arn:aws:dynamodb:*:*:table/products
          - Sid: GetStreamRecords
            Effect: Allow
            Action:
              - dynamodb:GetRecords
            Resource: arn:aws:dynamodb:*:*:table/products/stream/*
          - Sid: WriteLogStreamsAndGroups
            Effect: Allow
            Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: "*"
          - Sid: CreateLogGroup
            Effect: Allow
            Action:
              - logs:CreateLogGroup
            Resource: "*"

  ProductService:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/products/
      Handler: app.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Policies:
        - !Ref ProductDynamoDBAccess
